# **Numpy**

In [1]:
import numpy as np
import sys

# create a list
lst = [x for x in range(1, 11)]
print(lst, type(lst), sys.getsizeof(lst), lst.__sizeof__())

# create a array
arr = np.array([x for x in range(1, 11)])
print(arr, type(arr), sys.getsizeof(arr), arr.__sizeof__())

# create a array of int type
arrInt = np.array([x for x in range(1, 11)], int)
print(arrInt, type(arrInt), sys.getsizeof(arrInt), arrInt.__sizeof__())

# create a array of float type
arrFloat = np.array([x for x in range(2, 21, 2)], float)
print(arrFloat, type(arrFloat), sys.getsizeof(arrFloat), arrFloat.__sizeof__())

# create a array of bool type
arrBool = np.array([bool(x%2==0) for x in range(1, 11)], bool)
print(arrBool, type(arrFloat), sys.getsizeof(arrBool), arrBool.__sizeof__())


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'> 184 168
[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'> 192 192
[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'> 192 192
[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.] <class 'numpy.ndarray'> 192 192
[False  True False  True False  True False  True False  True] <class 'numpy.ndarray'> 122 122


### ***Compare execution time of list and array***
Which one is more fast.
- array is more fast than list.
- list takes more memory than array

In [2]:
%timeit [x**4 for x in range(2, 21, 2)] # list creation time
%timeit np.arange(2, 21, 2)**4 # array creation time
# %timeit function to calculate time for a statement

4.57 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
3.13 µs ± 66.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## **Array**

In [3]:
arr1 = np.array([x for x in range(1, 9)])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
arr2 = np.array([int(x) for x in input("Enter value : ").split()])
print(arr2)

Enter value :  1 2 3 4 5 6


[1 2 3 4 5 6]


### ***Dimensions in Arrays***
- 1D Arrays
- 2D Arrays
- 3D Arrays
- nD Arrays
- Use "ndim" method to check dimenstion.

In [5]:
# 1D Array
arr1d = np.array([x for x in range(1, 11)])
print("arr1d = ", arr1d)
print("Dimension = ", arr1d.ndim)
print()

# 2D Array
arr2d = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
print("arr2d = \n", arr2d)
print("Dimension = ", arr2d.ndim)
print()

# 3D Array
arr3d = np.array([
                    [
                        [1, 2, 3, 4],
                        [2, 4, 6, 8],
                        [3, 6, 9, 12]
                    ],
                    [
                        [10, 20, 30, 40],
                        [20, 40, 60, 80],
                        [30, 60, 90, 120]
                    ]
                ])
print("arr3d = \n", arr3d)   
print("Dimension = ", arr3d.ndim)
print()

# nd Array
arrnd = np.array([
    [
        [
            [x*1 for x in range(1, 6)],
            [x*2 for x in range(1, 6)],
            [x*3 for x in range(1, 6)],
            [x*4 for x in range(1, 6)]
        ],
        [
            [x+10 for x in range(1, 6)],
            [x+20 for x in range(1, 6)],
            [x+30 for x in range(1, 6)],
            [x+40 for x in range(1, 6)]
        ],
        [
            [x**1 for x in range(1, 6)],
            [x**2 for x in range(1, 6)],
            [x**3 for x in range(1, 6)],
            [x**4 for x in range(1, 6)]
        ]
    ]
])
print("arrnd = \n", arrnd)
print("Dimension = ", arrnd.ndim)
print() 
            

arr1d =  [ 1  2  3  4  5  6  7  8  9 10]
Dimension =  1

arr2d = 
 [[1 2 3]
 [2 4 6]
 [3 6 9]]
Dimension =  2

arr3d = 
 [[[  1   2   3   4]
  [  2   4   6   8]
  [  3   6   9  12]]

 [[ 10  20  30  40]
  [ 20  40  60  80]
  [ 30  60  90 120]]]
Dimension =  3

arrnd = 
 [[[[  1   2   3   4   5]
   [  2   4   6   8  10]
   [  3   6   9  12  15]
   [  4   8  12  16  20]]

  [[ 11  12  13  14  15]
   [ 21  22  23  24  25]
   [ 31  32  33  34  35]
   [ 41  42  43  44  45]]

  [[  1   2   3   4   5]
   [  1   4   9  16  25]
   [  1   8  27  64 125]
   [  1  16  81 256 625]]]]
Dimension =  4



In [6]:
arr3 = np.array([[1, 2, 3], [2, 4, 6]], int)
print(arr3)

[[1 2 3]
 [2 4 6]]


In [7]:
arr4 = np.array([[x for x in range(1, 11)], [y for y in range(2, 21, 2)]], ndmin=4)
print(arr4)
print(arr4.ndim)

[[[[ 1  2  3  4  5  6  7  8  9 10]
   [ 2  4  6  8 10 12 14 16 18 20]]]]
4


## **Create Numpy Array**
- Array filled with 0's
- Array filled with 1's
- Create an empty array
- An array with a range of elements
- Array diagonal element filled with 1's
- Create an array with values that are spaced linearly in a specified interval.

### **zeros**

In [8]:
arr_zero = np.zeros(4)
print(arr_zero)
print("\n")

arr_zero1 = np.zeros((3, 4), int)
print(arr_zero1)


[0. 0. 0. 0.]


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### **ones**

In [9]:
arr_ones = np.ones(5, int)
print(arr_ones)
print("\n")

arr_ones1 = np.ones((3, 4), int)
print(arr_ones1)


[1 1 1 1 1]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### **empty**

In [10]:
arr_empty = np.empty(5)
print(arr_empty)
print("\n")
arr_empty1 = np.empty((4,5), int)
print(arr_empty1)


[2.12843436e-316 0.00000000e+000 1.06688523e+224 2.70746011e-005
 6.94091743e-310]


[[41732178        0        0        0        0]
 [       0        0        0        0        0]
 [       0        0        0        0        0]
 [       0        0        0        0        0]]


### **arange**

In [11]:
arr_r = np.arange(5)
print(arr_r)
print()

arr_arange = np.arange(1, 20, 3)
print(arr_arange)
print()

arr_arange = np.arange(1, 20, 3, dtype="float")
print(arr_arange)

[0 1 2 3 4]

[ 1  4  7 10 13 16 19]

[ 1.  4.  7. 10. 13. 16. 19.]


### **Diagonal**

In [12]:
arr_dia = np.eye(3)
print(arr_dia)
print()

arr_d = np.eye(3, 4)
print(arr_d)
print()

arr_d = np.eye(3, 4, dtype="int")
print(arr_d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


### **linspace**

In [13]:
arr_lin = np.linspace(0, 10, 5)
print(arr_lin)
print()
arr_lin1 = np.linspace(0, 20, num=5)
print(arr_lin1)
print()
arr_lin1 = np.linspace(0, 20, 5, dtype="int")
print(arr_lin1)
print()
arr_lin1 = np.linspace(0, 20, num=5, dtype="int")
print(arr_lin1)

[ 0.   2.5  5.   7.5 10. ]

[ 0.  5. 10. 15. 20.]

[ 0  5 10 15 20]

[ 0  5 10 15 20]


### **repeat**

In [14]:
arr = np.repeat(3, 5)
print(arr)
print()

arr = np.repeat(7, 4, axis=0)
print(arr)
print()

# arr = np.repeat(9, 6, axis=1)  # Error

[3 3 3 3 3]

[7 7 7 7]



### **Numpy Array with Random Numbers**
- rand() # interval (0, 1)
- randn() # value closer to zero.
- randint(a, b, c) # interval [a, b]
- seed() 

In [15]:
# rand()
arr_rand = np.random.rand(4)
print(arr_rand)
print("\n")
arr_rand1 = np.random.rand(3, 4)
print(arr_rand1)

[0.17822795 0.7277228  0.95974705 0.11697778]


[[0.46816214 0.86302876 0.79023969 0.15318439]
 [0.45058294 0.53200012 0.1429604  0.87021037]
 [0.75803913 0.14901999 0.83946728 0.2276903 ]]


In [16]:
# randn()
arr_randn = np.random.randn(4)
print(arr_randn)
print("\n")
arr_randn1 = np.random.randn(3, 4)
print(arr_randn1)

[ 1.01516591  1.38153227  0.37346886 -1.49139085]


[[-0.19112054 -0.4389348  -0.797345   -0.76957866]
 [-0.22675973  0.84701001 -1.30146314 -0.38636105]
 [-0.04599618 -0.07468557  0.42243134 -0.47775185]]


In [17]:
# randint()
arr_randint = np.random.randint(1, 8, 5)
print(arr_randint)
print()

# seed()
np.random.seed(12) 
arr_randint = np.random.randint(1, 8, 5)
print(arr_randint)
print()

[5 2 2 4 4]

[4 4 7 6 2]



In [18]:
# randint()
arr_randint1 = np.random.randint(1, 9, (3, 4))
print(arr_randint1)
print()

# seed()
np.random.seed(12) 
arr_randint1 = np.random.randint(1, 9, (3, 4))
print(arr_randint1)
print()

[[3 4 4 5]
 [1 7 2 5]
 [6 6 2 3]]

[[4 4 7 6]
 [2 3 4 4]
 [5 1 7 2]]



In [19]:
# randint()
arr_randint2 = np.random.randint(1, 8, (3, 4, 5))
print(arr_randint2)

[[[5 6 6 2 3]
  [4 7 3 1 6]
  [1 5 6 3 2]
  [4 7 5 4 2]]

 [[7 1 3 7 3]
  [1 5 7 4 6]
  [2 6 7 1 1]
  [7 4 4 2 4]]

 [[1 2 7 2 1]
  [5 1 5 2 4]
  [5 6 4 6 4]
  [5 6 4 6 4]]]


In [20]:
arr_randint3 = np.random.randint(0, 9, (4, 5, 7, 7))
print(arr_randint3)
print(arr_randint3.ndim)
print(arr_randint3.shape)

[[[[0 6 6 3 2 4 3]
   [6 7 4 1 4 5 3]
   [5 0 2 6 4 7 6]
   [2 3 2 6 4 5 0]
   [0 5 4 0 3 7 6]
   [8 6 1 4 6 5 2]
   [4 0 8 4 4 3 7]]

  [[3 6 1 4 3 8 8]
   [6 8 4 4 1 4 1]
   [4 3 2 8 0 1 4]
   [6 5 4 2 0 1 2]
   [5 2 0 1 4 7 7]
   [1 6 1 3 0 1 8]
   [4 8 8 8 8 3 5]]

  [[1 6 3 2 3 1 3]
   [2 2 8 3 5 1 7]
   [4 0 8 3 1 4 7]
   [2 2 4 0 8 3 5]
   [2 4 7 5 0 2 4]
   [6 6 2 7 2 5 1]
   [5 3 7 7 1 2 1]]

  [[5 8 0 8 6 5 6]
   [4 7 8 7 1 8 2]
   [2 7 0 1 0 5 0]
   [0 7 4 3 2 6 3]
   [4 4 7 2 2 3 0]
   [3 7 8 1 6 1 8]
   [6 6 1 3 0 5 5]]

  [[3 3 7 5 1 7 7]
   [2 3 0 2 5 8 4]
   [3 0 1 8 4 8 0]
   [1 5 1 2 3 5 6]
   [0 8 3 4 4 2 7]
   [7 0 3 4 0 2 4]
   [2 2 5 1 2 2 2]]]


 [[[6 0 7 4 8 3 8]
   [8 7 4 2 2 3 3]
   [7 4 8 7 6 0 8]
   [0 6 7 4 0 1 6]
   [4 2 0 2 8 2 0]
   [5 0 3 0 8 1 0]
   [6 0 0 2 4 3 1]]

  [[5 0 2 2 8 5 0]
   [7 0 2 8 0 5 3]
   [5 7 6 6 4 6 1]
   [1 2 4 4 6 2 3]
   [4 4 3 0 8 7 5]
   [1 1 3 7 5 0 7]
   [8 5 0 5 1 4 6]]

  [[2 3 4 7 4 7 6]
   [4 6 3 1 2 4 2]
   [8 8 3 5 3 1

## **Data Type in Numpy Arrays**
- bool_
- int_
- Intc
- Intp
- int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_
- float16, float32, float64
- complex_
- complex64
- complex128

In [21]:
arr = np.random.randint(0, 9, (2, 3))
print(arr)
print(arr.dtype)

[[1 1 2]
 [2 4 6]]
int64


In [22]:
arr = np.random.randn(2, 3)
print(arr)
print(arr.dtype)

[[-1.13670265 -0.54675506  1.0915574 ]
 [ 0.39445575 -1.25352767 -2.13398235]]
float64


In [23]:
arr = np.array(['a', 'b', 'c', 'd', 'e'])
print(arr)
print(arr.dtype)

['a' 'b' 'c' 'd' 'e']
<U1


In [24]:
arr = np.array(['A', 'B', 'C', 1, 2, 3])
print(arr)
print(arr.dtype)

['A' 'B' 'C' '1' '2' '3']
<U21


### ***Data Types as Function***
- i : integer
- b : boolean
- u : unsigned integer
- f : float
- c : complex float
- m : timedelta
- M : datetime
- O : object
- S : string
- U : Unicode string
- V : the fixed chunk of memory for other types (void)

In [25]:
arr = np.arange(2, 20, 3, dtype = np.int8)
print(arr)
print(arr.dtype)

[ 2  5  8 11 14 17]
int8


In [26]:
arr = np.arange(2, 20, 3, dtype = np.float16)
print(arr)
print(arr.dtype)

[ 2.  5.  8. 11. 14. 17.]
float16


In [27]:
arr = np.arange(2, 20, 3, dtype = 'f')
print(arr)
print(arr.dtype)

[ 2.  5.  8. 11. 14. 17.]
float32


In [28]:
arr = np.arange(2, 20, 3, dtype = 'float')
print(arr)
print(arr.dtype)

[ 2.  5.  8. 11. 14. 17.]
float64


In [29]:
arr = np.arange(2, 20, 3)
n = np.float32(arr)
print(n)
print(n.dtype)

[ 2.  5.  8. 11. 14. 17.]
float32


In [30]:
arr = np.linspace(2, 20, 5, dtype=np.int_)
print(arr)
print(arr.dtype)

[ 2  6 11 15 20]
int64


In [31]:
arr = np.linspace(2, 20, 5)
print(arr)
print(arr.dtype)

new_data = np.int_(arr)
print(new_data)
print(new_data.dtype)

[ 2.   6.5 11.  15.5 20. ]
float64
[ 2  6 11 15 20]
int64


In [32]:
arr = np.arange(2, 20, 2).reshape(3, 3)
print(arr)
print("\n")
arr = np.linspace(2, 20, 9, dtype=np.int_).reshape(3, 3)
print(arr)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


[[ 2  4  6]
 [ 8 11 13]
 [15 17 20]]


In [33]:
arr = np.array([x for x in range(1, 9)], int)
print(arr)
print(arr.dtype)
print("\n")
x = arr.astype(float)
print(x)
print(x.dtype)


[1 2 3 4 5 6 7 8]
int64


[1. 2. 3. 4. 5. 6. 7. 8.]
float64


## **Arithmetic Operation on Arrays**
- a+b : np.add(a, b)
- a-b : np.subtract(a, b)
- a*b : np.multiply(a, b)
- a/b : np.divide(a, b)
- a%b : np.mod(a, b)
- a**b : np.power(a, b)
- 1/a : np.reciprocal(a)

In [34]:
a1 = np.linspace(2, 40, 9, dtype=np.int_)
print(a1)
a_sum = a1+3
print(a_sum)
print("\n")

a2 = np.linspace(1, 30 , 9, dtype=np.int_)
print(a2)
a_sum = a2*5
print(a_sum)


[ 2  6 11 16 21 25 30 35 40]
[ 5  9 14 19 24 28 33 38 43]


[ 1  4  8 11 15 19 22 26 30]
[  5  20  40  55  75  95 110 130 150]


In [35]:
# arithmetic operation on array
a1 = np.linspace(4, 70, 9, dtype=np.int_)
print("a1 = ", a1)
a2 = np.linspace(3, 12, 9, dtype=np.int_)
print("a2 = ", a2)
a3 = a1+a2
print("a1+a2 = ", a3)
a4 = a1-a2
print("a1-a2 = ", a4)
a5 = a1*a2
print("a1*a2 = ", a5)
a6 = a1//a2
print("a1//a2 = ", a6)
a7 = a1/a2
print("a1/a2 = ", a7)
a8 = a1%a2
print("a1%a2 = ", a8)
a9 = a1**a2
print("a1**a2 = ", a9)

a1 =  [ 4 12 20 28 37 45 53 61 70]
a2 =  [ 3  4  5  6  7  8  9 10 12]
a1+a2 =  [ 7 16 25 34 44 53 62 71 82]
a1-a2 =  [ 1  8 15 22 30 37 44 51 58]
a1*a2 =  [ 12  48 100 168 259 360 477 610 840]
a1//a2 =  [1 3 4 4 5 5 5 6 5]
a1/a2 =  [1.33333333 3.         4.         4.66666667 5.28571429 5.625
 5.88888889 6.1        5.83333333]
a1%a2 =  [ 1  0  0  4  2  5  8  1 10]
a1**a2 =  [                 64               20736             3200000
           481890304         94931877133      16815125390625
    3299763591802133  713342911662882601 6229145717836288000]


### **Aarithmetic Operation using Functions**

In [36]:
# 1D array
a1 = np.linspace(2, 80, 9, dtype=np.int_)
print("a1 = ", a1)
a2 = np.linspace(1, 40, 9, dtype=np.int_)
print("a2 = ", a2)
print("a1+a2 = ", np.add(a1, a2))
print("a1-a2 = ", np.subtract(a1, a2))
print("a1*a2 = ", np.multiply(a1, a2))
print("a1/a2 = ", np.divide(a1, a2))
print("a1%a2 = ", np.mod(a1, a2))
print("a1**a2 = ", np.power(a1, a2))
print("1/a1 = ", np.reciprocal(a1))
print("dot = ", a1.dot(a2))


a1 =  [ 2 11 21 31 41 50 60 70 80]
a2 =  [ 1  5 10 15 20 25 30 35 40]
a1+a2 =  [  3  16  31  46  61  75  90 105 120]
a1-a2 =  [ 1  6 11 16 21 25 30 35 40]
a1*a2 =  [   2   55  210  465  820 1250 1800 2450 3200]
a1/a2 =  [2.         2.2        2.1        2.06666667 2.05       2.
 2.         2.         2.        ]
a1%a2 =  [0 1 1 1 1 0 0 0 0]
a1**a2 =  [                  2              161051      16679880978201
 1003530086136274399 7757413047147151009  187601812243611648
 1152921504606846976 2801405922193178624                   0]
1/a1 =  [0 0 0 0 0 0 0 0 0]
dot =  10252


In [37]:
# 2D array
v1 = np.linspace(3, 50, 20, dtype=np.int_).reshape(4, 5)
print("v1 = \n", v1)
v2 = np.linspace(2, 25, 20, dtype=np.int_).reshape(4, 5)
print("v2 = \n", v2)
print("\n")

print("v1+v2 = \n", v1+v2) 
print("v1+v2 = \n", np.add(v1, v2))
print("\n")

print("v1-v2 = \n", v1-v2) 
print("v1-v2 = \n", np.subtract(v1, v2))
print("\n")

print("v1*v2 = \n", v1*v2) 
print("v1*v2 = \n", np.multiply(v1, v2))
print("\n")

print("v1/v2 = \n", v1/v2) 
print("v1/v2 = \n", np.divide(v1, v2))
print("\n")

print("v1%v2 = \n", v1%v2) 
print("v1%v2 = \n", np.mod(v1, v2))
print("\n")

print("v1**v2 = \n", v1**v2)
print("v1**v2 = \n", np.power(v1, v2))


v1 = 
 [[ 3  5  7 10 12]
 [15 17 20 22 25]
 [27 30 32 35 37]
 [40 42 45 47 50]]
v2 = 
 [[ 2  3  4  5  6]
 [ 8  9 10 11 12]
 [14 15 16 17 18]
 [20 21 22 23 25]]


v1+v2 = 
 [[ 5  8 11 15 18]
 [23 26 30 33 37]
 [41 45 48 52 55]
 [60 63 67 70 75]]
v1+v2 = 
 [[ 5  8 11 15 18]
 [23 26 30 33 37]
 [41 45 48 52 55]
 [60 63 67 70 75]]


v1-v2 = 
 [[ 1  2  3  5  6]
 [ 7  8 10 11 13]
 [13 15 16 18 19]
 [20 21 23 24 25]]
v1-v2 = 
 [[ 1  2  3  5  6]
 [ 7  8 10 11 13]
 [13 15 16 18 19]
 [20 21 23 24 25]]


v1*v2 = 
 [[   6   15   28   50   72]
 [ 120  153  200  242  300]
 [ 378  450  512  595  666]
 [ 800  882  990 1081 1250]]
v1*v2 = 
 [[   6   15   28   50   72]
 [ 120  153  200  242  300]
 [ 378  450  512  595  666]
 [ 800  882  990 1081 1250]]


v1/v2 = 
 [[1.5        1.66666667 1.75       2.         2.        ]
 [1.875      1.88888889 2.         2.         2.08333333]
 [1.92857143 2.         2.         2.05882353 2.05555556]
 [2.         2.         2.04545455 2.04347826 2.        ]]
v1/v2 = 
 [

In [38]:
v1 = np.linspace(3, 50, 20, dtype=np.int_).reshape(4, 5)
print("v1 = \n", v1)
v2 = np.linspace(2, 25, 20, dtype=np.int_).reshape(5, 4)
print("v2 = \n", v2)
print("\n")
adot = v1.dot(v2)
print("dot = ")
print(adot)

v1 = 
 [[ 3  5  7 10 12]
 [15 17 20 22 25]
 [27 30 32 35 37]
 [40 42 45 47 50]]
v2 = 
 [[ 2  3  4  5]
 [ 6  8  9 10]
 [11 12 14 15]
 [16 17 18 20]
 [21 22 23 25]]


dot = 
[[ 525  567  611  670]
 [1229 1345 1464 1610]
 [1923 2114 2307 2540]
 [2629 2895 3164 3485]]


## **Arithmetic Functions in NumPy Arrays**
- **np.min(x),    np.min(x, axis=0)** # axis=0 for column
- **np.max(x),    np.max(x, axis=1)** # axis=1 for rows
- **np.argmin(x)** : *return index number of min*,   np.argmin(x, axis=0) # axis=0 for column
- **np.argmax(x)** : *return index number of max*,   np.argman(x, axis=1) # axis=1 for rows
- **np.sqrt(x)**
- **np.sin(x)**
- **np.cos(x)**
- **np.cumsum(x)** # add the result of previous one and make next element
- **a.dot(b)**

In [39]:
arr = np.random.randint(10, 90, (4, 5))
print(arr)
print(arr.shape)
print(np.min(arr), np.argmin(arr))
print(np.max(arr), np.argmax(arr))


[[34 11 56 58 65]
 [51 89 10 78 27]
 [33 86 62 58 68]
 [27 70 80 21 60]]
(4, 5)
10 7
89 6


In [40]:
arr = np.random.randint(10, 90, (5, 4))
print(arr)
print(arr.shape)
print("min and max values along columns : ")
print("min : ", np.min(arr, axis=0), np.argmin(arr, axis=0)) # axis=0 for column
print("max : ", np.max(arr, axis=0), np.argmax(arr, axis=0)) 
print("min and max values along rows : ")
print("min : ", np.min(arr, axis=1), np.argmin(arr, axis=1)) # axis=1 for rows
print("max : ", np.max(arr, axis=1), np.argmax(arr, axis=1))
print("sqrt : ")
print(np.sqrt(arr))
print("sin : ")
print(np.sin(arr))
print("cos : ")
print(np.cos(arr))
print("cumsum : ")
print(np.cumsum(arr))

arr1 = arr
arr2 = np.random.randint(10, 90, (4, 5))
print("arr1 : \n", arr1)
print("arr2 : \n", arr2)
arr = arr1.dot(arr2)
print("dot arr : \n", arr)


[[46 46 44 51]
 [80 54 25 80]
 [29 85 52 83]
 [52 60 69 76]
 [49 56 19 34]]
(5, 4)
min and max values along columns : 
min :  [29 46 19 34] [2 0 4 4]
max :  [80 85 69 83] [1 2 3 2]
min and max values along rows : 
min :  [44 25 29 52 19] [2 2 0 0 2]
max :  [51 80 85 76 56] [3 0 1 3 1]
sqrt : 
[[6.78232998 6.78232998 6.63324958 7.14142843]
 [8.94427191 7.34846923 5.         8.94427191]
 [5.38516481 9.21954446 7.21110255 9.11043358]
 [7.21110255 7.74596669 8.30662386 8.71779789]
 [7.         7.48331477 4.35889894 5.83095189]]
sin : 
[[ 0.90178835  0.90178835  0.01770193  0.67022918]
 [-0.99388865 -0.55878905 -0.13235175 -0.99388865]
 [-0.66363388 -0.17607562  0.98662759  0.96836446]
 [ 0.98662759 -0.30481062 -0.11478481  0.56610764]
 [-0.95375265 -0.521551    0.14987721  0.52908269]]
cos : 
[[-0.43217794 -0.43217794  0.99984331  0.7421542 ]
 [-0.11038724 -0.82930983  0.99120281 -0.11038724]
 [-0.74805753 -0.98437664 -0.16299078  0.24954012]
 [-0.16299078 -0.95241298  0.99339038  0.824331

In [41]:
arr = np.arange(1, 9)
print("arr : ", arr)
print("cumsum : ", np.cumsum(arr))

arr :  [1 2 3 4 5 6 7 8]
cumsum :  [ 1  3  6 10 15 21 28 36]


## **shape & reshape**

In [42]:
arr = np.array([[x for x in range(1, 6)], [y for y in range(2, 11, 2)]])
print("arr : \n", arr)
print("shape : ", arr.shape)

arr = np.array([x for x in range(1, 10, 1)], ndmin=4)
print("arr : ", arr)
print(arr.shape)

arr = np.array([x for x in range(1, 10, 1)]).reshape(3, 3)
print("arr : \n", arr)
print(arr.shape)
print("arr : \n", arr.reshape(1, 9))
print("arr : \n", arr.reshape(9, 1))

arr : 
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
shape :  (2, 5)
arr :  [[[[1 2 3 4 5 6 7 8 9]]]]
(1, 1, 1, 9)
arr : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
arr : 
 [[1 2 3 4 5 6 7 8 9]]
arr : 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [43]:
arr = np.random.randint(10, 90, (6, 7))
print("arr : \n", arr)
print(arr.shape)
print(arr.ndim)

arr = arr.reshape(3, 14)
print("arr : \n", arr)
print(arr.shape)
print(arr.ndim)

arr = arr.reshape(7, 3, 2)
print("arr : \n", arr)
print(arr.shape)
print(arr.ndim)

arr = arr.reshape(-1) # convert it into 1D array
print("arr : ", arr)
print(arr.shape)
print(arr.ndim)

arr : 
 [[75 21 11 55 85 51 13]
 [34 68 53 80 88 56 27]
 [61 36 54 26 14 83 68]
 [84 13 68 26 47 31 76]
 [70 89 51 17 38 83 65]
 [10 74 47 25 85 46 76]]
(6, 7)
2
arr : 
 [[75 21 11 55 85 51 13 34 68 53 80 88 56 27]
 [61 36 54 26 14 83 68 84 13 68 26 47 31 76]
 [70 89 51 17 38 83 65 10 74 47 25 85 46 76]]
(3, 14)
2
arr : 
 [[[75 21]
  [11 55]
  [85 51]]

 [[13 34]
  [68 53]
  [80 88]]

 [[56 27]
  [61 36]
  [54 26]]

 [[14 83]
  [68 84]
  [13 68]]

 [[26 47]
  [31 76]
  [70 89]]

 [[51 17]
  [38 83]
  [65 10]]

 [[74 47]
  [25 85]
  [46 76]]]
(7, 3, 2)
3
arr :  [75 21 11 55 85 51 13 34 68 53 80 88 56 27 61 36 54 26 14 83 68 84 13 68
 26 47 31 76 70 89 51 17 38 83 65 10 74 47 25 85 46 76]
(42,)
1


In [44]:
arr = np.random.randint(10, 90, (2, 3, 4))
print("arr : \n", arr)
print(arr.shape)
print(arr.ndim)
arr = arr.reshape(6, 4)
print("arr : \n", arr)
arr = arr.reshape(-1)
print("arr : ", arr)

arr : 
 [[[66 10 22 81]
  [21 64 82 24]
  [68 58 20 19]]

 [[19 71 39 89]
  [11 83 22 44]
  [37 21 30 89]]]
(2, 3, 4)
3
arr : 
 [[66 10 22 81]
 [21 64 82 24]
 [68 58 20 19]
 [19 71 39 89]
 [11 83 22 44]
 [37 21 30 89]]
arr :  [66 10 22 81 21 64 82 24 68 58 20 19 19 71 39 89 11 83 22 44 37 21 30 89]


In [45]:
arr = np.random.randint(10, 90, (6, 4))
print("arr : \n", arr)
print(arr.shape)
print(arr.ndim)

arr = arr.reshape(4, 2, 3)
print("arr : \n", arr)
print(arr.shape)
print(arr.ndim)

arr = arr.reshape(3, 2, 4)
print("arr : \n", arr)
print(arr.shape)
print(arr.ndim)

arr = arr.reshape(-1)
print("arr : \n", arr)
print(arr.shape)
print(arr.ndim)


arr : 
 [[64 86 81 61]
 [45 32 14 36]
 [73 23 35 77]
 [46 73 66 70]
 [40 34 82 79]
 [80 29 70 79]]
(6, 4)
2
arr : 
 [[[64 86 81]
  [61 45 32]]

 [[14 36 73]
  [23 35 77]]

 [[46 73 66]
  [70 40 34]]

 [[82 79 80]
  [29 70 79]]]
(4, 2, 3)
3
arr : 
 [[[64 86 81 61]
  [45 32 14 36]]

 [[73 23 35 77]
  [46 73 66 70]]

 [[40 34 82 79]
  [80 29 70 79]]]
(3, 2, 4)
3
arr : 
 [64 86 81 61 45 32 14 36 73 23 35 77 46 73 66 70 40 34 82 79 80 29 70 79]
(24,)
1


In [46]:
a = np.arange(1, 10, 1).reshape(3, 3)
print(a)
b = np.arange(2, 20, 2).reshape(3, 3)
print(b)
print(np.dot(a, b))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]


## **Broadcasting NumPy Array**
- Same Dimension
- Any Condition : *A(1xn) + B(nx1) or A(1xn) + B(nxn) or A(nx1) + B(nxn)*
                                

In [47]:
a = np.random.randint(1, 9, (1, 3))
print("a : \n", a)
print()
b = np.random.randint(1, 9, (3, 1))
print("b : \n", b)
print()
# we know matrix a(1x3) and b(3x1) row=column so c = a+b and c(3x3)
c = a+b
print("c : \n", c)
print()


a : 
 [[7 5 8]]

b : 
 [[2]
 [3]
 [1]]

c : 
 [[ 9  7 10]
 [10  8 11]
 [ 8  6  9]]



In [48]:
a = np.random.randint(1, 9, (1, 3))
print("a : \n", a)
print()
b = np.random.randint(1, 9, (3, 3))
print("b : \n", b)
print()
c = a+b
print("c : \n", c)
print()


a : 
 [[6 4 5]]

b : 
 [[1 1 2]
 [1 2 5]
 [4 1 2]]

c : 
 [[ 7  5  7]
 [ 7  6 10]
 [10  5  7]]



In [49]:
a = np.random.randint(1, 9, (3, 1))
print("a : \n", a)
print()
b = np.random.randint(1, 9, (3, 3))
print("b : \n", b)
print()
c = a+b
print("c : \n", c)
print()

a : 
 [[3]
 [8]
 [6]]

b : 
 [[5 1 6]
 [8 1 1]
 [4 2 3]]

c : 
 [[ 8  4  9]
 [16  9  9]
 [10  8  9]]



In [50]:
a = np.random.randint(1, 9, (3, 1))
print("a : \n", a)
print()
b = np.random.randint(1, 9, (3, 7))
print("b : \n", b)
print()
c = a+b
print("c : \n", c)
print()

a : 
 [[1]
 [4]
 [2]]

b : 
 [[8 5 1 6 5 5 6]
 [2 8 5 5 8 3 2]
 [6 8 1 3 7 3 5]]

c : 
 [[ 9  6  2  7  6  6  7]
 [ 6 12  9  9 12  7  6]
 [ 8 10  3  5  9  5  7]]



In [51]:
a = np.random.randint(1, 9, (1, 4))
print("a : \n", a)
print()
b = np.random.randint(1, 9, (3, 4))
print("b : \n", b)
print()
c = a+b
print("c : \n", c)
print()

a : 
 [[8 6 6 7]]

b : 
 [[8 4 1 2]
 [3 4 5 6]
 [2 1 4 6]]

c : 
 [[16 10  7  9]
 [11 10 11 13]
 [10  7 10 13]]



## **Indexing & Slicing in NumPy Arrays**
- **arr_name[** _start_ **:** _end_ **:** _step_ **]** \
    _start_, _end_, _step_ could be +ve -ve anything
- Positive indexing and Negative indexing both posible like list
- Excluding the last value like in list

In [52]:
idx = np.array([x for x in range(0, 14)])
print(idx)
arr = np.array([x*3 for x in range(1, 15)])
print(arr)
print(arr.ndim)
print(arr.shape)
print()

print(arr[4])
print(arr[2:6])
print(arr[::2])
print(arr[::1])
print(arr[0:10:2])
print(arr[11:2:-1])
print(arr[2::3])
print(arr[::3])

print("======================================")

print(arr[-1])
print(arr[-10:-5])
print(arr[-10:-5:2])
print(arr[::-1])
print(arr[::-2])
print(arr[::-3])
print(arr[12:2:-1])
print(arr[12:2:-2])
print(arr[-2:-12:-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42]
1
(14,)

15
[ 9 12 15 18]
[ 3  9 15 21 27 33 39]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42]
[ 3  9 15 21 27]
[36 33 30 27 24 21 18 15 12]
[ 9 18 27 36]
[ 3 12 21 30 39]
42
[15 18 21 24 27]
[15 21 27]
[42 39 36 33 30 27 24 21 18 15 12  9  6  3]
[42 36 30 24 18 12  6]
[42 33 24 15  6]
[39 36 33 30 27 24 21 18 15 12]
[39 33 27 21 15]
[39 36 33 30 27 24 21 18 15 12]


In [53]:
arr = np.random.randint(10, 90, (8, 7, 6))
print(arr)
print(arr.ndim)
print(arr.shape)
print()
print(arr[2]); print()
print(arr[2][3]); print()
print(arr[2][3][1]); print()
print('Slicing : ')
print(arr[2:6]); print()
print("------------------------")
print(arr[2:6][2]); print()
print("------------------------")
print(arr[2:6][2][2:5]); print()
print("------------------------")
print(arr[2:6][2][2:5][1]); print()
print("------------------------")
print(arr[2:6][2][2:5][1][1:4]); print()
print("------------------------")
print(arr[3:])
print("------------------------")
print(arr[-4][:4])
print("------------------------")
print(arr[0:8:2])
print("------------------------")

print("=================================================")

print(arr[-2]); print()
print(arr[-2][-4]); print()
print(arr[-2][-4][-3]); print()
print("------------------------")
print(arr[-6:-2]); print()
print("------------------------")
print(arr[-6:-2][-2]); print()
print("------------------------")
print(arr[-6:-2][-2][-5:-2]); print()
print("------------------------")
print(arr[-6:-2][-2][-5:-2][-2][3]); print()
print("------------------------")
print(arr[-6:-2][-2][-5:-2][-2][-4]); print()
print("------------------------")


[[[79 48 42 73 70 29]
  [24 79 86 45 79 23]
  [72 41 23 71 34 69]
  [15 15 61 53 33 52]
  [18 12 83 52 50 19]
  [38 36 21 66 15 70]
  [31 79 81 83 42 70]]

 [[54 81 71 53 85 79]
  [72 16 11 49 14 14]
  [33 10 48 37 76 50]
  [48 60 72 12 44 89]
  [86 57 25 79 22 51]
  [15 52 70 45 29 65]
  [88 30 41 19 13 80]]

 [[29 15 31 58 10 71]
  [55 32 74 58 39 61]
  [12 52 75 23 16 52]
  [53 68 82 71 81 87]
  [74 69 82 82 49 69]
  [17 54 85 58 39 75]
  [27 44 28 50 13 89]]

 [[25 27 22 40 69 82]
  [47 55 26 67 61 40]
  [55 15 32 38 19 19]
  [77 29 22 38 14 10]
  [12 29 61 13 17 77]
  [21 17 11 38 66 84]
  [20 11 79 26 84 10]]

 [[39 51 27 67 29 28]
  [37 88 51 64 40 56]
  [52 38 62 71 28 63]
  [76 21 54 79 19 55]
  [58 67 47 28 86 86]
  [24 69 38 52 30 65]
  [39 63 51 20 13 66]]

 [[88 55 45 85 42 38]
  [68 43 74 54 73 59]
  [17 32 16 67 67 83]
  [81 55 60 47 31 23]
  [26 23 46 38 74 47]
  [42 47 66 28 64 65]
  [20 80 83 80 56 77]]

 [[42 38 47 13 59 78]
  [69 24 41 53 46 22]
  [54 16 30 58 81 40

In [54]:
arr = np.random.randint(10, 90, (5, 5))
print(arr)
print(arr.ndim)
print(arr.shape)
print()

data = np.array([x*10 for x in range(1, 6)])
print(data)
print()

arr[3] = data
print(arr)
print()

data = np.random.randint(1, 9, (2, 5))
print(data)
print()

arr[1:3] = data[:]
print(arr)

[[35 81 31 45 14]
 [27 37 70 68 76]
 [70 62 39 56 59]
 [11 32 42 70 33]
 [66 44 41 26 35]]
2
(5, 5)

[10 20 30 40 50]

[[35 81 31 45 14]
 [27 37 70 68 76]
 [70 62 39 56 59]
 [10 20 30 40 50]
 [66 44 41 26 35]]

[[7 4 6 4 7]
 [2 1 4 2 5]]

[[35 81 31 45 14]
 [ 7  4  6  4  7]
 [ 2  1  4  2  5]
 [10 20 30 40 50]
 [66 44 41 26 35]]


## **Iterating Numpy Arrays**
- **for lst in iter(arr)**
- **for mtx, lst in enumerate(arr)**
- **for val in nditer(arr)**
- **for idx, val in ndenumerate(arr)**

In [55]:
arr = np.random.randint(10, 90, 15)
print(arr)
print(arr.ndim)
print(arr.shape)
print()

for val in arr:
    print(val)


[29 50 14 81 50 20 47 69 49 19 63 61 42 81 47]
1
(15,)

29
50
14
81
50
20
47
69
49
19
63
61
42
81
47


In [56]:
np.random.seed(3)
arr = np.random.randint(10, 90, (8, 7))
print(arr)
print(arr.ndim)
print(arr.shape)
print()

for lst in arr:
    print(lst)

for lst in arr:
    for val in lst:
        print(val)

print()

[[34 13 66 82 10 31 29]
 [84 51 20 31 48 30 54]
 [49 24 36 32 76 12 73]
 [70 11 61 79 39 34 72]
 [17 53 43 89 58 47 30]
 [59 31 88 38 64 10 74]
 [28 73 47 66 66 81 47]
 [56 43 11 84 26 42 26]]
2
(8, 7)

[34 13 66 82 10 31 29]
[84 51 20 31 48 30 54]
[49 24 36 32 76 12 73]
[70 11 61 79 39 34 72]
[17 53 43 89 58 47 30]
[59 31 88 38 64 10 74]
[28 73 47 66 66 81 47]
[56 43 11 84 26 42 26]
34
13
66
82
10
31
29
84
51
20
31
48
30
54
49
24
36
32
76
12
73
70
11
61
79
39
34
72
17
53
43
89
58
47
30
59
31
88
38
64
10
74
28
73
47
66
66
81
47
56
43
11
84
26
42
26



In [57]:
arr = np.random.randint(10, 90, (8, 7))
print(arr)
print(arr.ndim)
print(arr.shape)
print() 
print("--------------------------------------------")
print()

for lst in iter(arr):
    print(lst)
print()
print("--------------------------------------------")
print()

for lst in iter(arr):
    for val in iter(lst):
        print(val)

[[28 85 65 23 47 40 58]
 [71 43 62 12 38 46 54]
 [58 69 84 64 31 66 49]
 [39 42 58 19 43 70 65]
 [21 20 86 78 54 54 29]
 [26 49 60 75 45 55 62]
 [11 28 73 12 30 72 32]
 [17 67 53 42 70 26 37]]
2
(8, 7)

--------------------------------------------

[28 85 65 23 47 40 58]
[71 43 62 12 38 46 54]
[58 69 84 64 31 66 49]
[39 42 58 19 43 70 65]
[21 20 86 78 54 54 29]
[26 49 60 75 45 55 62]
[11 28 73 12 30 72 32]
[17 67 53 42 70 26 37]

--------------------------------------------

28
85
65
23
47
40
58
71
43
62
12
38
46
54
58
69
84
64
31
66
49
39
42
58
19
43
70
65
21
20
86
78
54
54
29
26
49
60
75
45
55
62
11
28
73
12
30
72
32
17
67
53
42
70
26
37


In [58]:
arr = np.random.randint(10, 90, (8, 7))
print(arr)
print(arr.ndim)
print(arr.shape)
print() 
print("--------------------------------------------")

for val in np.nditer(arr):
    print(val)

[[63 18 30 18 34 88 86]
 [29 19 36 60 70 15 19]
 [42 23 54 81 46 52 82]
 [36 34 30 72 54 40 27]
 [42 63 49 70 42 43 61]
 [89 21 27 61 81 23 78]
 [73 51 23 87 70 57 46]
 [65 66 80 22 38 20 21]]
2
(8, 7)

--------------------------------------------
63
18
30
18
34
88
86
29
19
36
60
70
15
19
42
23
54
81
46
52
82
36
34
30
72
54
40
27
42
63
49
70
42
43
61
89
21
27
61
81
23
78
73
51
23
87
70
57
46
65
66
80
22
38
20
21


In [59]:
arr = np.random.randint(10, 90, (8, 7))
print(arr)
print(arr.ndim)
print(arr.shape)
print() 
print("--------------------------------------------")

for idx, val in np.ndenumerate(arr):
    print(idx, val)

[[45 59 82 44 21 69 14]
 [10 66 55 81 31 44 39]
 [52 17 40 86 85 49 67]
 [59 54 31 51 81 44 25]
 [32 55 46 50 62 19 29]
 [79 64 22 36 45 34 62]
 [53 33 60 28 74 81 63]
 [42 88 36 13 47 31 33]]
2
(8, 7)

--------------------------------------------
(0, 0) 45
(0, 1) 59
(0, 2) 82
(0, 3) 44
(0, 4) 21
(0, 5) 69
(0, 6) 14
(1, 0) 10
(1, 1) 66
(1, 2) 55
(1, 3) 81
(1, 4) 31
(1, 5) 44
(1, 6) 39
(2, 0) 52
(2, 1) 17
(2, 2) 40
(2, 3) 86
(2, 4) 85
(2, 5) 49
(2, 6) 67
(3, 0) 59
(3, 1) 54
(3, 2) 31
(3, 3) 51
(3, 4) 81
(3, 5) 44
(3, 6) 25
(4, 0) 32
(4, 1) 55
(4, 2) 46
(4, 3) 50
(4, 4) 62
(4, 5) 19
(4, 6) 29
(5, 0) 79
(5, 1) 64
(5, 2) 22
(5, 3) 36
(5, 4) 45
(5, 5) 34
(5, 6) 62
(6, 0) 53
(6, 1) 33
(6, 2) 60
(6, 3) 28
(6, 4) 74
(6, 5) 81
(6, 6) 63
(7, 0) 42
(7, 1) 88
(7, 2) 36
(7, 3) 13
(7, 4) 47
(7, 5) 31
(7, 6) 33


In [60]:
arr = np.random.randint(10, 90, (8, 7, 5))
print(arr)
print(arr.ndim)
print(arr.shape)
print() 

print("--------------------------------------------")

print()
for idx, lst in enumerate(arr):
    print(lst)
    print(idx, lst.ndim, lst.shape)
print()

print("--------------------------------------------")

print()
for mtx, lst2d in enumerate(arr):
    for idx, lst1d in enumerate(lst2d):
        print(lst1d)
        print(mtx, idx)

[[[86 28 44 16 80]
  [29 70 87 49 74]
  [70 22 50 14 52]
  [68 31 10 45 87]
  [31 78 79 51 80]
  [55 42 75 81 77]
  [35 36 88 32 86]]

 [[21 40 89 13 80]
  [56 57 24 85 15]
  [89 70 44 75 48]
  [60 69 28 39 73]
  [31 36 22 33 27]
  [40 46 17 84 35]
  [20 61 11 63 22]]

 [[78 13 72 44 59]
  [52 70 14 31 82]
  [29 11 28 79 65]
  [59 85 13 84 29]
  [49 54 16 72 36]
  [10 46 64 88 47]
  [46 33 28 84 54]]

 [[41 86 21 34 36]
  [14 66 10 30 65]
  [20 15 69 19 64]
  [71 48 43 78 85]
  [56 56 31 59 18]
  [35 22 75 85 30]
  [63 39 42 17 30]]

 [[77 32 33 19 43]
  [25 23 38 38 55]
  [81 79 76 40 12]
  [75 29 68 53 30]
  [38 61 50 88 32]
  [45 66 70 28 73]
  [54 52 34 54 42]]

 [[14 50 82 64 62]
  [21 61 86 54 58]
  [36 12 80 28 40]
  [74 43 31 79 64]
  [35 15 69 39 56]
  [62 57 35 32 43]
  [62 66 23 65 31]]

 [[34 17 56 43 67]
  [30 39 16 29 64]
  [59 39 87 25 50]
  [89 64 43 30 17]
  [50 21 60 40 23]
  [80 22 10 18 26]
  [34 86 69 60 50]]

 [[61 61 72 31 73]
  [80 19 60 21 11]
  [38 54 30 60 67

In [61]:
arr = np.random.randint(10, 90, (8, 7, 5))
print(arr)
print(arr.ndim)
print(arr.shape)
print() 

for mtx, lst2d in enumerate(arr):
    for lst, lst1d in enumerate(lst2d):
        for pos, val in enumerate(lst1d):
            print("(", mtx, lst, pos, ")", val)

[[[14 43 81 22 43]
  [53 40 74 77 32]
  [10 83 69 80 59]
  [70 74 76 71 27]
  [66 24 54 53 56]
  [67 38 23 64 14]
  [70 43 11 31 31]]

 [[22 39 69 64 33]
  [76 63 63 45 51]
  [38 66 23 74 36]
  [65 69 16 89 43]
  [36 85 77 76 43]
  [87 47 69 59 43]
  [25 66 27 23 64]]

 [[78 42 32 87 76]
  [69 27 59 40 70]
  [73 34 45 84 35]
  [45 55 32 21 22]
  [29 13 65 43 38]
  [88 29 48 18 63]
  [52 89 24 74 31]]

 [[68 66 33 23 64]
  [87 20 41 63 59]
  [32 85 48 48 15]
  [22 77 28 13 34]
  [72 72 22 14 32]
  [24 74 34 41 53]
  [49 38 12 43 89]]

 [[16 64 31 81 10]
  [87 32 54 45 84]
  [11 65 64 85 31]
  [45 36 64 57 28]
  [70 43 72 68 45]
  [16 31 26 28 25]
  [19 87 86 87 44]]

 [[78 29 78 54 63]
  [33 14 56 80 87]
  [54 88 32 25 83]
  [88 28 23 73 46]
  [66 63 36 52 25]
  [13 18 66 56 77]
  [89 48 48 21 87]]

 [[65 13 36 55 56]
  [74 15 87 51 34]
  [68 51 86 17 25]
  [19 62 74 74 43]
  [30 76 18 59 30]
  [22 78 53 35 26]
  [57 32 49 62 59]]

 [[15 64 11 10 62]
  [35 19 36 55 26]
  [19 54 79 45 81

In [62]:
# nditer()
arr = np.random.randint(10, 90, (8, 7, 5))
print(arr)
print(arr.ndim)
print(arr.shape)
print() 
print("--------------------------------------------")

for val in np.nditer(arr):
    print(val)

[[[89 20 65 63 53]
  [47 21 54 18 41]
  [30 27 43 77 20]
  [73 49 64 61 61]
  [23 18 42 63 71]
  [30 76 49 40 64]
  [48 35 58 37 35]]

 [[38 32 22 21 17]
  [81 34 58 81 24]
  [89 12 25 51 43]
  [69 23 51 88 58]
  [84 77 10 24 24]
  [19 55 85 80 10]
  [60 24 49 22 65]]

 [[17 50 74 72 86]
  [27 66 76 29 58]
  [24 23 49 49 87]
  [70 54 32 48 70]
  [19 51 35 71 49]
  [54 59 38 87 52]
  [64 45 85 54 58]]

 [[24 59 86 12 15]
  [88 17 24 27 14]
  [79 65 18 58 10]
  [53 38 30 52 52]
  [77 70 43 68 54]
  [67 37 54 51 57]
  [16 41 61 44 27]]

 [[62 23 71 74 11]
  [21 65 26 87 61]
  [14 23 73 69 70]
  [35 78 57 18 57]
  [82 75 75 54 43]
  [18 84 24 63 74]
  [24 20 87 40 69]]

 [[54 71 79 16 40]
  [27 71 41 25 24]
  [26 52 84 13 28]
  [70 28 72 12 59]
  [56 31 14 37 48]
  [88 76 33 58 36]
  [66 50 50 19 86]]

 [[38 59 19 47 19]
  [49 34 21 24 19]
  [89 50 36 83 51]
  [59 38 49 29 36]
  [67 50 88 48 87]
  [72 14 59 66 11]
  [84 81 44 10 55]]

 [[12 13 62 88 46]
  [53 48 62 35 40]
  [29 62 77 56 45

In [63]:
# ndenumerate()
arr = np.random.randint(10, 90, (8, 7, 5))
print(arr)
print(arr.ndim)
print(arr.shape)
print() 

for idx, val in np.ndenumerate(arr):
    print(idx, val)

[[[24 10 45 68 43]
  [80 79 56 42 71]
  [20 25 84 82 45]
  [14 89 57 21 77]
  [25 23 50 74 36]
  [45 28 68 24 52]
  [76 57 50 47 37]]

 [[84 57 50 73 85]
  [63 38 81 72 60]
  [55 20 44 72 63]
  [87 68 21 19 60]
  [74 79 60 21 83]
  [57 85 12 40 63]
  [70 49 71 40 87]]

 [[41 11 55 64 79]
  [85 40 66 82 34]
  [37 57 42 85 56]
  [80 46 52 73 73]
  [58 85 53 73 73]
  [19 20 68 35 70]
  [61 51 62 84 40]]

 [[25 47 18 16 28]
  [60 35 48 46 58]
  [28 70 82 29 10]
  [38 55 67 16 29]
  [31 34 69 40 10]
  [67 64 74 15 63]
  [54 15 77 49 36]]

 [[63 25 56 70 51]
  [70 71 84 48 57]
  [11 18 25 15 68]
  [82 81 68 12 62]
  [84 27 63 62 41]
  [16 86 40 69 40]
  [61 57 18 54 24]]

 [[77 89 11 45 33]
  [60 44 38 19 57]
  [43 34 27 20 26]
  [52 44 89 55 18]
  [69 42 70 30 66]
  [29 16 38 54 83]
  [13 71 36 86 66]]

 [[17 48 67 16 88]
  [69 17 34 50 32]
  [53 51 37 56 29]
  [75 69 80 65 28]
  [39 52 77 38 32]
  [81 45 80 68 36]
  [20 52 29 13 87]]

 [[44 75 84 59 24]
  [11 58 24 74 76]
  [83 45 15 27 25

## **Copy vs View in Numpy Arrays**
- Both are use to copy the array
- arr.view() for the shallow copy
- arr.copy() for the deep copy

In [64]:
# copy() # Deep Copy
print("copy() : ")
arr1 = np.array([x for x in range(1, 5)])
print(arr1)
cp = arr1.copy()
print(cp)
print()

cp[2] = 45
print(arr1)
print(cp)
print()

arr1[1] = 7
print(arr1)
print(cp)
print()

print("----------------------------------------------")

# view() # Shallow copy
print("view() : ")
arr2 = np.array([x*2 for x in range(1, 5)])
print(arr2)
vw = arr2.view()
print(vw)
print()

vw[2] = 14
print(arr2)
print(vw)
print()

arr2[1] = 78
print(arr2)
print(vw)
print()

copy() : 
[1 2 3 4]
[1 2 3 4]

[1 2 3 4]
[ 1  2 45  4]

[1 7 3 4]
[ 1  2 45  4]

----------------------------------------------
view() : 
[2 4 6 8]
[2 4 6 8]

[ 2  4 14  8]
[ 2  4 14  8]

[ 2 78 14  8]
[ 2 78 14  8]



## **Joining & Split Numpy Arrays**
### **Using :** *concatenate, stack, array_split*
- **Join Array :** Joining means putting contents of two or more arrays in a single array.

### **Join Array**

In [65]:
# joinint of 2 1D array
arr1 = np.array([x for x in range(1, 5)])
arr2 = np.array([x*7 for x in range(1, 5)])
print(arr1)
print(arr2)

arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4]
[ 7 14 21 28]
[ 1  2  3  4  7 14 21 28]


In [66]:
arr1 = np.array([x for x in range(1, 10)]).reshape(3, 3)
arr2 = np.array([x*7 for x in range(1, 10)]).reshape(3, 3)
print(arr1); print()
print(arr2); print()

arr = np.concatenate((arr1, arr2), axis=1) # axis=1 : row     similar to hstack
print(arr); print()

arr = np.concatenate((arr1, arr2), axis=0) # axis=0 : col     similar to vstack
print(arr); print()


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 7 14 21]
 [28 35 42]
 [49 56 63]]

[[ 1  2  3  7 14 21]
 [ 4  5  6 28 35 42]
 [ 7  8  9 49 56 63]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 7 14 21]
 [28 35 42]
 [49 56 63]]



### **stack, hstack, vstack, dstack Arrays**

In [67]:
arr1 = np.array([x for x in range(1, 10)]).reshape(3, 3)
arr2 = np.array([x*10 for x in range(1, 10)]).reshape(3, 3)
print(arr1); print()
print(arr2); print()

print("===================================================")
print("axis=1 : ")
arr = np.stack((arr1, arr2), axis=1) # axis=1 : row
print(arr)
print(arr.shape)
print()
print("---------------------------------------------------")

print("axis=0 : ")
arr = np.stack((arr1, arr2), axis=0) # axis=0 : col
print(arr)
print(arr.shape)
print()
print("---------------------------------------------------")

print("axis=-1 : ")
arr = np.stack((arr1, arr2), axis=-1) # axis=-1 : height
print(arr)
print(arr.shape)
print()
print("---------------------------------------------------")

print()
print("===================================================")
print()

print("stack : ")
arr = np.stack((arr1, arr2))
print(arr); print()
print("---------------------------------------------------")

print("hstack : ")
arr = np.hstack((arr1, arr2)) # h: horizontal
print(arr); print()
print("---------------------------------------------------")

print("vstack : ")
arr = np.vstack((arr1, arr2)) # v: vertical
print(arr); print()
print("---------------------------------------------------")

print("dstack : ")
arr = np.dstack((arr1, arr2)) # d: height
print(arr); print()
print("---------------------------------------------------")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]

axis=1 : 
[[[ 1  2  3]
  [10 20 30]]

 [[ 4  5  6]
  [40 50 60]]

 [[ 7  8  9]
  [70 80 90]]]
(3, 2, 3)

---------------------------------------------------
axis=0 : 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]
(2, 3, 3)

---------------------------------------------------
axis=-1 : 
[[[ 1 10]
  [ 2 20]
  [ 3 30]]

 [[ 4 40]
  [ 5 50]
  [ 6 60]]

 [[ 7 70]
  [ 8 80]
  [ 9 90]]]
(3, 3, 2)

---------------------------------------------------


stack : 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

---------------------------------------------------
hstack : 
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]

---------------------------------------------------
vstack : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]

---------------------------------------------------
dstack : 
[[[ 1 10]
  [ 2 20]
  [ 3 30]]



### **array_split Array**

In [68]:
arr = np.array([x for x in range(1, 10)])
print(arr); print()
sarr = np.array_split(arr, 3)
print(sarr); print()

print(sarr[0]); print()
print(sarr[1]); print()
print(sarr[2]); print()

for a in iter(sarr):
    print(a)

[1 2 3 4 5 6 7 8 9]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

[1 2 3]

[4 5 6]

[7 8 9]

[1 2 3]
[4 5 6]
[7 8 9]


In [69]:
arr = np.array([x for x in range(1, 10)])
print(arr); print()
sarr = np.array_split(arr, 2)
print(sarr); print()

sarr = np.array_split(arr, 3)
print(sarr); print()

sarr = np.array_split(arr, 4)
print(sarr); print()

sarr = np.array_split(arr, 5)
print(sarr); print()

[1 2 3 4 5 6 7 8 9]

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]



In [70]:
arr = np.random.randint(10, 90, (3, 4))
print(arr); print()

sarr = np.array_split(arr, 3)
print(sarr); print()

sarr = np.array_split(arr, 4)
print(sarr); print()

sarr = np.array_split(arr, 5)
print(sarr); print()

[[41 48 27 78]
 [67 81 63 85]
 [45 85 33 85]]

[array([[41, 48, 27, 78]]), array([[67, 81, 63, 85]]), array([[45, 85, 33, 85]])]

[array([[41, 48, 27, 78]]), array([[67, 81, 63, 85]]), array([[45, 85, 33, 85]]), array([], shape=(0, 4), dtype=int64)]

[array([[41, 48, 27, 78]]), array([[67, 81, 63, 85]]), array([[45, 85, 33, 85]]), array([], shape=(0, 4), dtype=int64), array([], shape=(0, 4), dtype=int64)]



In [71]:
arr = np.random.randint(10, 90, (3, 4)).reshape(-1)
print(arr); print()

sarr = np.array_split(arr, 3)
print(sarr); print()

sarr = np.array_split(arr, 4)
print(sarr); print()

sarr = np.array_split(arr, 5)
print(sarr); print()

sarr = np.array_split(arr, 6)
print(sarr); print()


[32 12 18 51 44 82 10 37 32 40 73 61]

[array([32, 12, 18, 51]), array([44, 82, 10, 37]), array([32, 40, 73, 61])]

[array([32, 12, 18]), array([51, 44, 82]), array([10, 37, 32]), array([40, 73, 61])]

[array([32, 12, 18]), array([51, 44, 82]), array([10, 37]), array([32, 40]), array([73, 61])]

[array([32, 12]), array([18, 51]), array([44, 82]), array([10, 37]), array([32, 40]), array([73, 61])]



In [72]:
# split along row
arr = np.random.randint(10, 90, (3, 4))
print(arr)
print("-----------------------------------")
print()

sarr = np.array_split(arr, 2, axis=1)
for ar in sarr:
    print(ar); print()
print("-----------------------------------")
print()

sarr = np.array_split(arr, 3, axis=1)
for ar in sarr:
    print(ar); print()
print("-----------------------------------")
print()

sarr = np.array_split(arr, 4, axis=1)
for ar in sarr:
    print(ar); print()
print("-----------------------------------")
print()

sarr = np.array_split(arr, 5, axis=1)
for ar in sarr:
    print(ar); print()
print("-----------------------------------")
print()

[[16 58 10 53]
 [37 23 14 53]
 [23 40 81 35]]
-----------------------------------

[[16 58]
 [37 23]
 [23 40]]

[[10 53]
 [14 53]
 [81 35]]

-----------------------------------

[[16 58]
 [37 23]
 [23 40]]

[[10]
 [14]
 [81]]

[[53]
 [53]
 [35]]

-----------------------------------

[[16]
 [37]
 [23]]

[[58]
 [23]
 [40]]

[[10]
 [14]
 [81]]

[[53]
 [53]
 [35]]

-----------------------------------

[[16]
 [37]
 [23]]

[[58]
 [23]
 [40]]

[[10]
 [14]
 [81]]

[[53]
 [53]
 [35]]

[]

-----------------------------------



In [73]:
# axis=0
arr = np.random.randint(10, 90, (3, 4))
print(arr)
print("-----------------------------------")
print()

sarr = np.array_split(arr, 2, axis=0)
for ar in sarr:
    print(ar); print()
print("-----------------------------------")
print()

sarr = np.array_split(arr, 3, axis=0)
for ar in sarr:
    print(ar); print()
print("-----------------------------------")
print()

sarr = np.array_split(arr, 4, axis=0)
for ar in sarr:
    print(ar); print()
print("-----------------------------------")
print()

sarr = np.array_split(arr, 5, axis=0)
for ar in sarr:
    print(ar); print()
print("-----------------------------------")
print()

[[50 36 67 11]
 [83 51 47 89]
 [71 20 59 35]]
-----------------------------------

[[50 36 67 11]
 [83 51 47 89]]

[[71 20 59 35]]

-----------------------------------

[[50 36 67 11]]

[[83 51 47 89]]

[[71 20 59 35]]

-----------------------------------

[[50 36 67 11]]

[[83 51 47 89]]

[[71 20 59 35]]

[]

-----------------------------------

[[50 36 67 11]]

[[83 51 47 89]]

[[71 20 59 35]]

[]

[]

-----------------------------------



## **NumPy Arrays Functions**
- **Search :** Search an array for a certain value, and return the indexes that get a match 
- **Search Sorted :** Which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain\
    the search order.
- **Sort :** Sort the array
- **Filter Array :** Getting some elements out of an existing array and creating a new array out of them.

### **Search**

In [74]:
arr = np.random.randint(1, 9, 16)
print(arr)
print()

[5 2 7 5 5 3 3 3 3 7 7 2 4 3 6 5]



In [75]:
x = np.where(arr == 7) # array of index
print(x); print()

x = np.where((arr%2) == 0) # array of index
print(x)

(array([ 2,  9, 10]),)

(array([ 1, 11, 12, 14]),)


### **Searchsorted**

In [76]:
arr = np.array([x for x in range(1, 10) if x!=7 and x!=5])
print(arr); print()

x = np.searchsorted(arr, 7)
print(x)
x = np.searchsorted(arr, 7, side="right")
print(x)
x = np.searchsorted(arr, 7, side="left")
print(x)


[1 2 3 4 6 8 9]

5
5
5


In [77]:
arr = np.array([x for x in range(1, 10) if x%2!=0])
print(arr); print()

x = np.searchsorted(arr, [2, 4, 6, 8])
print(x)

[1 3 5 7 9]

[1 2 3 4]


### **Sort**

In [78]:
arr = np.random.randint(10, 90, 10)
print(arr); print()

ar = np.sort(arr) # reverse=True not work
print(ar)


[70 33 44 64 17 72 42 30 33 75]

[17 30 33 33 42 44 64 70 72 75]


In [79]:
# sort every row of 2D array
arr = np.random.randint(10, 90, (4, 5))
print(arr); print()

ar = np.sort(arr) # reverse=True not work
print(ar)


[[55 17 54 27 74]
 [78 16 46 59 42]
 [49 85 18 43 33]
 [51 43 60 47 78]]

[[17 27 54 55 74]
 [16 42 46 59 78]
 [18 33 43 49 85]
 [43 47 51 60 78]]


### **Filter Array**

In [80]:
arr = np.random.randint(10, 90, 6)
print(arr); print()
flt = [True, False, False, True, False, True]
print(flt)
ar = arr[flt] # size of arr = size of flt
print(ar)

[42 47 76 35 20 62]

[True, False, False, True, False, True]
[42 35 62]


## **Numpy Arrays Functions**
### **Arithmetic Functions :**
- **Shuffle**
- **Unique**
- **Resize**
- **Flatten**
- **Ravel**

In [81]:
arr = np.arange(1, 10)
print(arr)
np.random.shuffle(arr)
print(arr)


[1 2 3 4 5 6 7 8 9]
[8 6 1 9 2 3 7 5 4]


In [82]:
arr = np.random.randint(1, 9, 20)
print(arr)
x = np.unique(arr)
print(x)

x = np.unique(arr, return_index=True, return_counts=True)
print(x)

[8 3 1 6 2 6 2 4 2 7 5 3 3 5 5 6 6 6 7 6]
[1 2 3 4 5 6 7 8]
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 2,  4,  1,  7, 10,  3,  9,  0]), array([1, 3, 3, 1, 3, 6, 2, 1]))


In [83]:
arr = np.arange(1, 10)
print(arr); print()

ar = np.resize(arr, (2, 2))
print(ar); print()

ar = np.resize(arr, (2, 3))
print(ar); print()

ar = np.resize(arr, (3, 3))
print(ar); print()

ar = np.resize(arr, (4, 3))
print(ar); print()

ar = np.resize(arr, (4, 5))
print(ar); print()

[1 2 3 4 5 6 7 8 9]

[[1 2]
 [3 4]]

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]

[[1 2 3 4 5]
 [6 7 8 9 1]
 [2 3 4 5 6]
 [7 8 9 1 2]]



### **Flatten, Ravel**
**Order : {'C', 'F', 'A', 'K'} Optional**
- 'C' means to flatten in row-major (C-Style) order.
- 'F' means to flatten in column-major (Fortran-style) order.
- 'A' means to flatten in column-major order if `a` is Fortran *contiguous* in memory,\
    row-major order otherwise.
- 'K' means to flatten `a` in the order the elements occur in memory
- The default is 'C'
    

In [84]:
arr = np.arange(1, 10)
arr = np.resize(arr, (3, 3))
print(arr); print()

print("Flatten : ")
print(arr.flatten())
print(arr.flatten(order="A"))
print(arr.flatten(order="C"))
print(arr.flatten(order="F"))
print(arr.flatten(order="K"))
print()
print("Ravel : ")
print(arr.ravel())
print(arr.ravel(order="A"))
print(arr.ravel(order="C"))
print(arr.ravel(order="F"))
print(arr.ravel(order="K"))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flatten : 
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]

Ravel : 
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]


## **Numpy Arrays Functions**
### **Insert, append and Delete Function**


### **Insert :** 
np.insert(_arrayName_, _position_, _value_)

In [85]:
arr = np.arange(1, 10)
print(arr); print()

ar = np.insert(arr, 1, 40)
print(ar); print()

ar = np.insert(arr, [1, 3], [78, 54])
print(ar); print()

idx = [ 1, 3, 5, 7]
data = [23, 43, 76, 90] # data type change will give error
ar = np.insert(arr, idx, data)
print(ar); print()

ar = np.append(arr, 44)
print(ar)

ar = np.append(arr, 4.6)
print(ar)

[1 2 3 4 5 6 7 8 9]

[ 1 40  2  3  4  5  6  7  8  9]

[ 1 78  2  3 54  4  5  6  7  8  9]

[ 1 23  2  3 43  4  5 76  6  7 90  8  9]

[ 1  2  3  4  5  6  7  8  9 44]
[1.  2.  3.  4.  5.  6.  7.  8.  9.  4.6]


In [86]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr); print()

ar = np.insert(arr, 2, 16, axis=1)
print(ar); print()

ar = np.insert(arr, 2, 16, axis=0)  # float value are not allow
print(ar); print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2 16  3]
 [ 4  5 16  6]
 [ 7  8 16  9]]

[[ 1  2  3]
 [ 4  5  6]
 [16 16 16]
 [ 7  8  9]]



In [87]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr); print()

ar = np.insert(arr, 2, [10, 20, 30])
print(ar); print()

ar = np.insert(arr, 2, [10, 20, 30], axis=1) # size of column = size of data
print(ar); print()

ar = np.insert(arr, 2, [10, 20, 30], axis=0) # size of row = size of data
print(ar); print()

ar = np.append(arr, 44)
print(ar); print()

ar = np.append(arr, [[11, 22, 33]], axis=0)
print(ar); print()

ar = np.append(arr, [[11], [22], [33]], axis=1)
print(ar); print()


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 1  2 10 20 30  3  4  5  6  7  8  9]

[[ 1  2 10  3]
 [ 4  5 20  6]
 [ 7  8 30  9]]

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [ 7  8  9]]

[ 1  2  3  4  5  6  7  8  9 44]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]]

[[ 1  2  3 11]
 [ 4  5  6 22]
 [ 7  8  9 33]]



### **Transpose**

In [88]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr); print()
print(arr.T); print()
print(np.transpose(arr)); print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]



### **Delete :**
np.delete(_arrayName, index_)

In [89]:
arr = np.arange(1, 10)
print("arr : ")
print(arr); print()
print("---------------------------------")
dar = np.delete(arr, 4)
print(dar); print()

dar = np.delete(arr, [2, 4, 6])
print(dar); print()

dar = np.delete(arr, -1)
print(dar); print()

dar = np.delete(arr, [-1, -3, -5])
print(dar); print()

arr : 
[1 2 3 4 5 6 7 8 9]

---------------------------------
[1 2 3 4 6 7 8 9]

[1 2 4 6 8 9]

[1 2 3 4 5 6 7 8]

[1 2 3 4 6 8]



## **Matrix in Numpy Arrays**

### **Difference b/w array and matrix**

In [90]:
arr = np.array([[1, 2, 3], [2, 4, 6]])
print(arr)
print(type(arr))
print()

mtx = np.matrix([[1, 2, 3], [2, 4, 6]])
print(mtx)
print(type(mtx))
print()

[[1 2 3]
 [2 4 6]]
<class 'numpy.ndarray'>

[[1 2 3]
 [2 4 6]]
<class 'numpy.matrix'>



### **Arithmetic Operation In Matrix**
- Addition +
- Substraction -
- Division /
- Division //
- Remainder %
- Multiplication * # condition: M1(nxm) & M2(pxn)
- Dot m1.dot(m2) # condition: M1(nxm) & M2(pxn)
- Exponent ** Not Possible

In [91]:
mtx1 = np.matrix([[x*4 for x in range(1, 4)], [x*5 for x in range(1, 4)]])
print("mtx1 : ")
print(mtx1)
print()

mtx2 = np.matrix([[x for x in range(1, 4)], [x*2 for x in range(1, 4)]])
print("mtx2 : ")
print(mtx2)
print()

print("Addition : ")
print(mtx1+mtx2)
print()

print("Substraction : ")
print(mtx1-mtx2)
print()

print("Multiplication : ")
# print(mtx1*mtx2) # Error row != col
print(mtx1*mtx2.T)
print()

print("Dot : ")
# print(mtx1.dot(mtx2))  # Error row != col
print(mtx1.dot(mtx2.T))
print()

print("Division : ")
print(mtx1/mtx2)
print()

print("Division : ")
print(mtx1//mtx2)
print()

print("Remainder : ")
print(mtx1%mtx2)
print()

# Exponent not work with matrix **

mtx1 : 
[[ 4  8 12]
 [ 5 10 15]]

mtx2 : 
[[1 2 3]
 [2 4 6]]

Addition : 
[[ 5 10 15]
 [ 7 14 21]]

Substraction : 
[[3 6 9]
 [3 6 9]]

Multiplication : 
[[ 56 112]
 [ 70 140]]

Dot : 
[[ 56 112]
 [ 70 140]]

Division : 
[[4.  4.  4. ]
 [2.5 2.5 2.5]]

Division : 
[[4 4 4]
 [2 2 2]]

Remainder : 
[[0 0 0]
 [1 2 3]]



### **Matrix Function in Numpy Arrays**
- **Transpose**
- **Swapaxes**
- **Inverse**
- **Power**
- **Determinate**

### ***Transpose & Swapaxes***

In [92]:
# np.mat()
# np.matrix()
# Both are same

mtx = np.mat(np.random.randint(1, 9, (3, 5)))
print("mtx : ")
print(mtx)
print(type(mtx))
print()

# transpose
print("mtx transpose : ")
print(np.transpose(mtx))
print()

print(mtx.T)
print()

# swapaxes
print("mtx swapaxes : ")
print(np.swapaxes(mtx, 0, 1))
print()

print(np.swapaxes(mtx, 0, -1))
print()

mtxS = np.swapaxes(mtx, 0, 1)
print(np.swapaxes(mtxS, 1, 0))
print()

print(np.swapaxes(mtxS, -1, 0))
print()

print(np.swapaxes(mtx, 1, -1))
print()


mtx : 
[[4 1 8 4 8]
 [6 5 1 3 8]
 [5 2 4 5 2]]
<class 'numpy.matrix'>

mtx transpose : 
[[4 6 5]
 [1 5 2]
 [8 1 4]
 [4 3 5]
 [8 8 2]]

[[4 6 5]
 [1 5 2]
 [8 1 4]
 [4 3 5]
 [8 8 2]]

mtx swapaxes : 
[[4 6 5]
 [1 5 2]
 [8 1 4]
 [4 3 5]
 [8 8 2]]

[[4 6 5]
 [1 5 2]
 [8 1 4]
 [4 3 5]
 [8 8 2]]

[[4 1 8 4 8]
 [6 5 1 3 8]
 [5 2 4 5 2]]

[[4 1 8 4 8]
 [6 5 1 3 8]
 [5 2 4 5 2]]

[[4 1 8 4 8]
 [6 5 1 3 8]
 [5 2 4 5 2]]



### ***Inverse***

In [93]:
mtx = np.mat(np.random.randint(1, 10, (2, 2)))
print(mtx)
print(type(mtx))
print()

imtx = np.linalg.inv(mtx)
print(imtx)
print()

[[3 9]
 [5 5]]
<class 'numpy.matrix'>

[[-0.16666667  0.3       ]
 [ 0.16666667 -0.1       ]]



In [94]:
mtx = np.mat(np.random.randint(1, 10, (3, 3)))
print(mtx)
print(type(mtx))
print()

imtx = np.linalg.inv(mtx)
print(imtx)
print()

[[8 2 4]
 [9 5 4]
 [1 8 4]]
<class 'numpy.matrix'>

[[-0.11111111  0.22222222 -0.11111111]
 [-0.2962963   0.25925926  0.03703704]
 [ 0.62037037 -0.57407407  0.2037037 ]]



In [95]:
mtx = np.mat(np.random.randint(-90, 90, (4, 4)))
print(mtx)
print(type(mtx))
print()

imtx = np.linalg.inv(mtx)
print(imtx)
print()

[[-33 -34 -80  13]
 [-60  63  58  81]
 [ 59  66 -44  39]
 [-43 -61 -58  60]]
<class 'numpy.matrix'>

[[-0.0155838  -0.00738222  0.00709061  0.0087336 ]
 [ 0.01204616  0.00611774  0.00341832 -0.01309086]
 [-0.01306895  0.0007072  -0.00354385  0.00418039]
 [-0.01155478  0.00161273  0.00513118  0.01365775]]



### ***Power***
- **np.linalg.matrix_power(_matrixName_, n)** \
    n could be n<0, n=0, n>0
- if `n=0` : Identity Matrix
- if `n>0` : Matrix x Power
- if `n<0` : Inverse x Power

In [96]:
mtx = np.matrix(np.random.randint(-90, 90, (4, 4)))
print(mtx)
print(type(mtx))
print()

# n=0
pmtx = np.linalg.matrix_power(mtx, 0)
print(pmtx)
print()

# n>0
pmtx = np.linalg.matrix_power(mtx, 2)
print(pmtx)
print()

# n<0
pmtx = np.linalg.matrix_power(mtx, -2) # inverse * power
print(pmtx)
print()

[[ 79   9 -75  86]
 [ -1  57  14 -54]
 [  3  46  19  39]
 [-67  77  77  -8]]
<class 'numpy.matrix'>

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

[[  245  4396  -602  2695]
 [ 3524  -274 -3019 -2186]
 [-2365  6526  3783 -1797]
 [-4603  6712  6950 -6853]]

[[-1.54297859e-03  2.77518480e-04  2.41837649e-03 -1.32946231e-03]
 [ 2.84220602e-04  4.58442059e-05 -1.86516703e-04  1.46057144e-04]
 [-1.60226932e-03  5.24712813e-05  2.39186538e-03 -1.27404058e-03]
 [-3.10193004e-04 -8.82877348e-05  6.18674636e-04 -4.01974533e-04]]



### ***Determinate***
- **np.linalg.det(_matrixName_)**

In [97]:
mtx = np.matrix(np.random.randint(1, 10, (2, 2)))
print(mtx)
print(type(mtx))
print()

dmtx = np.linalg.det(mtx)
print(dmtx)
print()


[[7 6]
 [7 3]]
<class 'numpy.matrix'>

-21.0



In [98]:
mtx = np.matrix(np.random.randint(1, 10, (3, 3)))
print(mtx)
print(type(mtx))
print()

dmtx = np.linalg.det(mtx)
print(dmtx)
print()


[[2 3 8]
 [1 6 2]
 [6 4 6]]
<class 'numpy.matrix'>

-181.99999999999997



In [99]:
mtx = np.matrix(np.random.randint(-90, 90, (5, 5)))
print(mtx)
print(type(mtx))
print()

dmtx = np.linalg.det(mtx)
print(dmtx)
print()


[[ 48  35   7  84 -48]
 [ 67  32 -44  84 -68]
 [ 25 -47  88  39 -66]
 [ 47  12   2  81 -76]
 [-23  18  38 -55 -81]]
<class 'numpy.matrix'>

643427861.0000001



## **Typecasting**

In [105]:
## to_numpy() only work with pandas

lst = [[1, 2, 3, 4], [2, 4, 6, 8]]
print(lst)
print(type(lst))
print()

lst2arr = np.asarray(lst)
print(lst2arr)
print(type(lst2arr))
print()

lst2mtx = np.asmatrix(lst)
print(lst2mtx)
print(type(lst2mtx))
print()

print("============================================")
print()

arr = np.array([[1, 2, 3], [2, 4, 6]])
print(arr)
print(type(arr))
print()

arr2lst = list(arr)
print(arr2lst)
print(type(arr2lst))
print()

arr2mtx = np.asmatrix(arr)
print(arr2mtx)
print(type(arr2mtx))

print("============================================")
print()

mtx = np.matrix([[1, 2, 3], [2, 4, 6]])
print(mtx)
print(type(mtx))
print()

mtx2lst = list(mtx)
print(mtx2lst)
print(type(mtx2lst))
print()

mtx2arr = np.asarray(mtx)
print(mtx2arr)
print(type(mtx2arr))
print()


[[1, 2, 3, 4], [2, 4, 6, 8]]
<class 'list'>

[[1 2 3 4]
 [2 4 6 8]]
<class 'numpy.ndarray'>

[[1 2 3 4]
 [2 4 6 8]]
<class 'numpy.matrix'>


[[1 2 3]
 [2 4 6]]
<class 'numpy.ndarray'>

[array([1, 2, 3]), array([2, 4, 6])]
<class 'list'>

[[1 2 3]
 [2 4 6]]
<class 'numpy.matrix'>

[[1 2 3]
 [2 4 6]]
<class 'numpy.matrix'>

[matrix([[1, 2, 3]]), matrix([[2, 4, 6]])]
<class 'list'>

[[1 2 3]
 [2 4 6]]
<class 'numpy.ndarray'>

